### PR TITLE
Updated index.html

### PR DESCRIPTION
**Pull request by Annoyed-Raven**
I added a function to count the words.

### CODE REVIEW

**Comment by MahdiRahbar** [comment]
@Annoyed-Raven  It all looks good to me. However, there is a part that can make conflict in some JS functions. The ```show``` id used in the HTML ```span``` tag as well as in your JS function is a very generic id to use. Would you please change that ID name to something more specific such as ```misspelled-counter``` or something unique? In this way, we can decrease the chance of conflict.

**Review by MahdiRahbar — CHANGES_REQUESTED** [review]
@Annoyed-Raven It all looks good to me. However, there is a part that can make conflict in some JS functions. The ```show``` id used in the HTML ```span``` tag as well as in your JS function is a very generic id to use. Would you please change that ID name to something more specific such as ```misspelled-counter``` or something unique? In this way, we can decrease the chance of conflict.

**Comment by Annoyed-Raven** [comment]
@MahdiRahbar
I updated the file to change the id for both calls to word_count :) so that there should be no conflicts in Js I appreciate you pointing that out to me.
@nicoprudencio we still need you to review and approve the change as the secondary :)

**Review by MahdiRahbar — APPROVED** [review]
@Annoyed-Raven Awesome!

**Review by nicoprudencio — APPROVED** [review]

**Pull request merged**
